### ISSUE TITLE
[BUG]: I keep forgetting the title because it's partially filled out.

### ISSUE THREAD

**Issue by jdlcdl** [EverydayBitcoiner/seedsigner#7]
### Is there an existing request for this feature?

- [X] I have searched the existing issues

### Feature Description

This should be a feature request, not a bug, but I'm a hacker... as you can see.

### Do you want to put up a bounty for this feature?

- [ ] I am willing to put up a bounty for this feature.

**Comment by EverydayBitcoiner** [comment]
Yes, I wish there was a way to lock the first part of the title, but I haven't seen one yet.

**Comment by EverydayBitcoiner** [comment]
You can change the title, yes, but the label is still for and enhancement. We could just take out the default first part of the title as that is optional.

**Comment by jdlcdl** [comment]
Closing these test issues in your repo @EverydayBitcoiner.  Thank you for having set these up!
